template_path: code_deploy.yaml
stack_name: codedeploy
parameters:

  Department: "CompOnc"
  Project: "genie"
  OwnerEmail: "thomas.yu@sagebase.org"

  KeyName: "phccp-autodeploy"
  TagKey: "Name"
  TagValue: "phc-cp"
  ApplicationName: "phccp-autodeploy"
  DeploymentGroupName: "phccp-autodeploy-group"
  GithubCommit: "563adedb730ee7743ae6482bb68a668562ab2050"
  GithubRepository: "Sage-Bionetworks/phccp-codedeploy"