sudo: false
language: python
python: 3.6
cache: pip
fast_finish: true
branches:
  only:
  - develop
  # - prod
install:
  - wget https://github.com/Sage-Bionetworks/infra-utils/archive/master.zip -O /tmp/infra-utils.zip
  - unzip -j -n /tmp/infra-utils.zip -x "infra-utils-master/.gitignore" "infra-utils-master/LICENSE" "infra-utils-master/*.md" "infra-utils-master/aws/*"
  - ./setup_aws_cli.sh || travis_terminate 1
  - pip install yamllint cfn-lint
  - pip install git+git://github.com/cloudreach/sceptre@v2.1.2
  - pip install git+git://github.com/zaro0508/sceptre-ssm-resolver.git
  - pip install git+git://github.com/zaro0508/sceptre-date-resolver.git
  - pip install git+git://github.com/Sage-Bionetworks/sceptre-provisioner-hooks.git
stages:
  - name: validate
  - name: deploy
    if: type = push
jobs:
  include:
    - stage: validate
      script:
        - yamllint ./config ./templates
        #- ./lint_stack.sh -l ./config/prod || travis_terminate 1
        - cfn-lint ./templates/**/* -i W1020
    - stage: deploy
      script:
        #- ./lint_stack.sh -r || travis_terminate 1
        - travis_wait 30 sceptre launch $TRAVIS_BRANCH --yes
        - bash deploy-templates.sh
      # deploy:
      #   - provider: s3
      #     access_key_id: "$ACCESS_KEY_ID"
      #     secret_access_key: "$SECRET_ACCESS_KEY"
      #     bucket: "phc-cp-dev-codedeploys3bucket-fu73x4w3tqo1"  
      #     skip_cleanup: true
      #     local_dir: target
      #     upload-dir: travis-builds
      #   - provider: codedeploy
      #     revision_type: s3
      #     key: travis-builds/deploy.zip
      #     bucket: "phc-cp-dev-codedeploys3bucket-fu73x4w3tqo1"  
      #     access_key_id: "$ACCESS_KEY_ID"
      #     secret_access_key: "$SECRET_ACCESS_KEY"
      #     application: "phc-cp-dev-CodeDeployApplication-Y1W5SLLMGLQJ"
      #     deployment_group: "phc-cp-dev-DeploymentGroup-K9APV8K0C8B9"
      #     region: "us-east-1"
