template_path: code_deploy.yaml
stack_name: sbcp-codedeploy
dependencies:
  - develop/code_deploy_essentials.yaml
parameters:

  Department: "CompOnc"
  Project: "sbcp"
  OwnerEmail: "thomas.yu@sagebase.org"

  # KeyName: "phccp-autodeploy"
  KeyName: "tomnew"
  TagKey: "Name"
  TagValue: "sbcp"
  # ApplicationName: "sbcp-autodeploy"
  # DeploymentGroupName: "sbcp-autodeploy-group"
  SSLCertificateIdArn: "arn:aws:acm:us-east-1:563295687221:certificate/38635e28-7aca-46c1-8c0c-2e54f7560909"
  CodeDeployEC2RoleInstanceProfile: !stack_output_external sbcp-codedeploy-essentials::CodeDeployEC2RoleInstanceProfile
  #sandcastle vpc
  VpcId: vpc-0e9b80dc470a797d5
  #public subnets
  Subnets: "subnet-02f2acd15e5be53cd,subnet-031359c53fce9b312,subnet-0f19d4c62f9ab0f2c"